### PR TITLE
fix #209 autocomplete click bug

### LINKED ISSUE #209: autocomplete click not working
When the user clicks on an option the curtain disappears but the said option doesn't get selected

### PR DESCRIPTION
**Pull request by Arual90**

### CODE REVIEW

File: src/autocomplete/index.js [hunk 1]
```diff
@@ -4,38 +4,41 @@ import props from './props';
...
   ----------*/
   _handleKeyboardInputs(evt) {
     // If Enter
-    if(evt.keyCode == 13 && this._currentHint != undefined) {
-      // this.setSelected(this._currentHint);
-      this.set('selected', this._currentHint);
-      this.querySelector('input-clab input').blur();
-      this.results = [];
-      return;
+    if(evt.keyCode === 13 && this._currentHint !== undefined) {
```
Comment (StefanoMagrassi) [inline src/autocomplete/index.js]: @Arual90 would be better:

```js
typeof this._currentHint !== 'undefined'
```

File: src/autocomplete/index.js [hunk 2]
```diff
@@ -4,38 +4,41 @@ import props from './props';
...
+      return this.setSelected(this._currentHint);
     }
 
     //If Arrows
-    if(this.results.length > 0 && evt.keyCode == 38 && this._currentHint != undefined) {
+    if(this.results.length > 0 && evt.keyCode === 38 && this._currentHint !== undefined) {
```
Comment (StefanoMagrassi) [inline src/autocomplete/index.js]: @Arual90 same as above

File: src/autocomplete/index.js [hunk 3]
```diff
@@ -4,38 +4,41 @@ import props from './props';
...
       evt.preventDefault();
       this._handleArrows('up');
       return;
     }
-    if(this.results.length > 0 && evt.keyCode == 40 && this._currentHint != undefined) {
+    if(this.results.length > 0 && evt.keyCode === 40 && this._currentHint !== undefined) {
```
Comment (StefanoMagrassi) [inline src/autocomplete/index.js]: @Arual90 same as above

File: src/autocomplete/index.js [hunk 4]
```diff
@@ -47,12 +50,12 @@ class AutoCompleteClab {
...
         composed: true
       }));
-      if(typeof this._interval == 'number') {
+      if(typeof this._interval === 'number') {
         window.clearTimeout(this._interval);
         this._interval = undefined;
       }
 
-      if(this.url != undefined) {
+      if(this.url !== undefined) {
```
Comment (StefanoMagrassi) [inline src/autocomplete/index.js]: @Arual90 same as above

File: src/autocomplete/index.js [hunk 5]
```diff
@@ -140,23 +169,25 @@ class AutoCompleteClab {
...
 
   _handleArrows(type) {
-    let HIdx = getIndex(this._currentHint, this.results);
+    const HIdx = getIndex(this._currentHint, this.results);
     let item;
     switch(type) {
       case 'up':
         item = this.results[HIdx - 1];
-        if(typeof item == 'object') {
+        if(typeof item === 'object') {
```
Comment (StefanoMagrassi) [inline src/autocomplete/index.js]: @Arual90 `typof item === 'object'` it's a bit too generic... Can we do a better check?

File: src/autocomplete/index.js [hunk 6]
```diff
@@ -140,23 +169,25 @@ class AutoCompleteClab {
...
           this._currentHint = item;
           this.querySelector('curtain-clab').scrollToHighlight(HIdx - 1, true);
         }
         break;
       case 'down':
         item = this.results[HIdx + 1];
-        if(typeof item == 'object') {
+        if(typeof item === 'object') {
```
Comment (StefanoMagrassi) [inline src/autocomplete/index.js]: @Arual90 same as previous comment

File: src/autocomplete/index.js [hunk 7]
```diff
@@ -167,13 +198,13 @@ class AutoCompleteClab {
...
   _setOptions(promise) {
-    promise().then((resp) => {
+    promise().then(resp => {
       this.set('options', resp);
     });
   }
 
   _changedSelected(val, old) {
-    if(val != undefined && Object.keys(val).length > 0) {
+    if(val !== undefined && Object.keys(val).length > 0) {
```
Comment (StefanoMagrassi) [inline src/autocomplete/index.js]: @Arual90 same as above
